# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
