# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_by', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteapp.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to='quoteapp.User'),
        ),
    ]
