# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_auto_20161026_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quote', to='quoteapp.User'),
        ),
    ]
